// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:minha_ebd/models/aula.dart';
import 'package:minha_ebd/models/classe.dart';
import 'package:minha_ebd/models/igreja.dart';
import 'package:minha_ebd/models/professor.dart';
import 'package:minha_ebd/models/superintendente.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AulaAdapter());
    registerAdapter(ClasseAdapter());
    registerAdapter(IgrejaAdapter());
    registerAdapter(ProfessorAdapter());
    registerAdapter(SuperintendenteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AulaAdapter());
    registerAdapter(ClasseAdapter());
    registerAdapter(IgrejaAdapter());
    registerAdapter(ProfessorAdapter());
    registerAdapter(SuperintendenteAdapter());
  }
}
